### ISSUE TITLE
Pedro Martinez (1992-2009) not counted for Nationals - Red Sox

### ISSUE THREAD

**Issue by Hbunce1561** [slxmmy999/InfiniteImmaculateGrid#29]

**Comment by meidlinger** [comment]
I just noticed this today also.  Several combinations for Pedro don't work.  Might be related to https://github.com/slxmmy999/InfiniteImmaculateGrid/issues/10 ?

**Comment by slxmmy999** [comment]
This issue should now be fixed. Let me know if you still have this error.
