### ISSUE TITLE
Make sure request URL's are safe

### ISSUE THREAD

**Issue by bingus17** [slxmmy999/InfiniteImmaculateGrid#4]

**Comment by slxmmy999** [comment]
Some names (Travis d'Arnaud) I believe may not be URL safe and will not work due to a 500 error if used. Will look more into this and make sure to provide checks on URL's before making requests.

**Comment by slxmmy999** [comment]
It seems the issue may be with MLB search not liking the apostrophe. I will look into possible workarounds for this issue or other causes that I'm just not seeing.
